version: '3.4'

services:
    web:
        image: jobotwar-webapp
        restart: always
        build:
            context: ./jobotwar-webapp
            dockerfile: ./Dockerfile
        ports:
            - 80:80
        depends_on:
            - api
    api:
        image: jobotwar
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8666:8666
        environment: 
            - DBURL=jdbc:postgresql://db/${DB_SCHEMA}?user=${DB_USER}&password=${DB_PWD}
        depends_on:
            - db
    db:
        image: postgres:${POSTGRES_TAG}
        restart: always
        volumes:
            - ${DB_LOCAL_PATH}:/var/lib/postgresql/data
            - ./jobotwar-web/src/main/resources/sql/init:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_PASSWORD=${DB_PWD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_SCHEMA}
            - PGDATA=/var/lib/postgresql/data/${DB_SCHEMA}
